// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxILruB4iSJ2-UXW49rQJdOuAtkBhCQeM',
    appId: '1:822873193911:web:04c353d38be56d0826fc32',
    messagingSenderId: '822873193911',
    projectId: 'nhs22thapril',
    authDomain: 'nhs22thapril.firebaseapp.com',
    storageBucket: 'nhs22thapril.firebasestorage.app',
    measurementId: 'G-1780P4Q5WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hQ-6ic6Vl90HxG4TkPgd40UztJukvFY',
    appId: '1:822873193911:android:516eebd35d80cfe126fc32',
    messagingSenderId: '822873193911',
    projectId: 'nhs22thapril',
    storageBucket: 'nhs22thapril.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZynW5byKeCntOImwZsf28mH00j4lzUJI',
    appId: '1:822873193911:ios:3e9efcf759e6649226fc32',
    messagingSenderId: '822873193911',
    projectId: 'nhs22thapril',
    storageBucket: 'nhs22thapril.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxILruB4iSJ2-UXW49rQJdOuAtkBhCQeM',
    appId: '1:822873193911:web:44c39cd77c19371d26fc32',
    messagingSenderId: '822873193911',
    projectId: 'nhs22thapril',
    authDomain: 'nhs22thapril.firebaseapp.com',
    storageBucket: 'nhs22thapril.firebasestorage.app',
    measurementId: 'G-PWM6QSX5EQ',
  );
}
